import { Order, Meal, TimeSlot, UserMetrics } from '../customer-types/dashboard';

export const mockOrders: Order[] = [
  {
    id: 'ORD-DEMO1',
    meal: 'Butter Chicken',
    restaurant: 'Punjab Grill',
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=400',
    status: 'cooking',
    pickupTime: '12:30 PM',
    pickupSlotId: '3',
    estimatedReady: '3 min',
    price: 249,
    quantity: 1,
    paymentStatus: 'paid',
    paymentMethod: 'upi',
    kitchenQueuePosition: 1,
    addOns: ['Extra Butter'],
    spiceLevel: 'medium',
    specialInstructions: '',
    createdAt: Date.now() - 600000,
    timeSaved: 18,
  },
  {
    id: 'ORD-DEMO2',
    meal: 'Hyderabadi Biryani',
    restaurant: 'Paradise Biryani',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400',
    status: 'preparing',
    pickupTime: '1:00 PM',
    pickupSlotId: '4',
    estimatedReady: '12 min',
    price: 299,
    quantity: 2,
    paymentStatus: 'cash',
    paymentMethod: 'cash',
    kitchenQueuePosition: 2,
    addOns: ['Raita', 'Papad'],
    spiceLevel: 'spicy',
    specialInstructions: 'Less oil please',
    createdAt: Date.now() - 300000,
    timeSaved: 22,
  },
];

export const mockMeals: Meal[] = [
  {
    id: '1',
    name: 'Butter Chicken',
    restaurant: 'Punjab Grill',
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=400',
    price: 249,
    prepTime: 15,
    rating: 4.9,
    category: 'North Indian',
  },
  {
    id: '2',
    name: 'Masala Dosa',
    restaurant: 'Saravana Bhavan',
    image: 'https://images.unsplash.com/photo-1668236543090-82eb5eaf59fd?w=400',
    price: 129,
    prepTime: 10,
    rating: 4.8,
    category: 'South Indian',
  },
  {
    id: '3',
    name: 'Hyderabadi Biryani',
    restaurant: 'Paradise Biryani',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400',
    price: 299,
    prepTime: 20,
    rating: 4.9,
    category: 'Biryani',
  },
  {
    id: '4',
    name: 'Pani Puri',
    restaurant: 'Chaat Corner',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=400',
    price: 79,
    prepTime: 5,
    rating: 4.7,
    category: 'Street Food',
  },
  {
    id: '5',
    name: 'Paneer Tikka',
    restaurant: 'Barbeque Nation',
    image: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=400',
    price: 199,
    prepTime: 12,
    rating: 4.8,
    category: 'North Indian',
  },
  {
    id: '6',
    name: 'Chole Bhature',
    restaurant: 'Haldiram\'s',
    image: 'https://images.unsplash.com/photo-1626132647523-66c9af4e09f8?w=400',
    price: 149,
    prepTime: 10,
    rating: 4.6,
    category: 'North Indian',
  },
];

export const mockTimeSlots: TimeSlot[] = [
  { id: '1', time: '11:30 AM', queueLevel: 'low',    availableSlots: 8,  estimatedWait: 0 },
  { id: '2', time: '12:00 PM', queueLevel: 'medium', availableSlots: 4,  estimatedWait: 3 },
  { id: '3', time: '12:30 PM', queueLevel: 'high',   availableSlots: 1,  estimatedWait: 8 },
  { id: '4', time: '1:00 PM',  queueLevel: 'medium', availableSlots: 5,  estimatedWait: 2 },
  { id: '5', time: '1:30 PM',  queueLevel: 'low',    availableSlots: 10, estimatedWait: 0 },
  { id: '6', time: '2:00 PM',  queueLevel: 'low',    availableSlots: 12, estimatedWait: 0 },
];

export const mockUserMetrics: UserMetrics = {
  timeSaved: 47,
  loyaltyPoints: 2450,
  activeOrders: 2,
  ordersThisMonth: 18,
  streak: 7,
  foodWasteReduced: 2.7,
  queueTimesSaved: 340,
};