import { Order, Meal, TimeSlot, UserMetrics } from '../customer-types/dashboard';

const butterChicken     = '/customer-assets/butter-chicken.jpg';
const masalaDosa        = '/customer-assets/masala-dosa.jpg';
const hyderabadiBiryani = '/customer-assets/hydrebadi-biryani.jpg';
const paneerTikka       = '/customer-assets/paneer-tikka.jpg';
const choleBhature      = '/customer-assets/chole-bhature.jpg';
const idliSambhar       = '/customer-assets/idli-sambhar.jpg';
const vadaPav           = '/customer-assets/vada-pav.jpg';
const dalMakhani        = '/customer-assets/dal-makhani.jpg';
const gulabJamun        = '/customer-assets/gulab-jamun.jpg';
const rajasthaniThali   = '/customer-assets/rajasthani-thali.jpg';
const lucknowiBiryani   = '/customer-assets/lucknowi-biryani.jpg';
const samosa            = '/customer-assets/samosa.jpg';
const chocolateDonuts   = '/customer-assets/chocolate-donuts.jpg';
const poha              = '/customer-assets/poha.jpg';
const palakPaneer       = '/customer-assets/palak-paneer.jpg';
const chickenKorma      = '/customer-assets/chicken-korma.jpg';
const kadaiPaneer       = '/customer-assets/kadai-paneer.jpg';
const pizza             = '/customer-assets/pizza.jpg';
const butterGarlicNaan  = '/customer-assets/butter-garlic-naan.jpg';
const muttonRoganJosh   = '/customer-assets/mutton-rogan-josh.jpg';
const prawnMasala       = '/customer-assets/prawn-masala.jpg';

export const mockOrders: Order[] = [
  {
    id: 'ORD-DEMO1',
    meal: 'Butter Chicken',
    restaurant: 'Punjab Grill',
    image: butterChicken,
    status: 'cooking',
    pickupTime: '12:30 PM',
    pickupSlotId: '3',
    estimatedReady: '3 min',
    price: 249,
    quantity: 1,
    paymentStatus: 'paid',
    paymentMethod: 'upi',
    kitchenQueuePosition: 1,
    addOns: ['Extra Butter'],
    spiceLevel: 'medium',
    specialInstructions: '',
    createdAt: Date.now() - 600000,
    timeSaved: 18,
  },
  {
    id: 'ORD-DEMO2',
    meal: 'Hyderabadi Biryani',
    restaurant: 'Paradise Biryani',
    image: hyderabadiBiryani,
    status: 'confirmed',
    pickupTime: '1:00 PM',
    pickupSlotId: '4',
    estimatedReady: '12 min',
    price: 299,
    quantity: 2,
    paymentStatus: 'cash',
    paymentMethod: 'cash',
    kitchenQueuePosition: 2,
    addOns: ['Raita', 'Papad'],
    spiceLevel: 'spicy',
    specialInstructions: 'Less oil please',
    createdAt: Date.now() - 300000,
    timeSaved: 22,
  },
];

export const mockMeals: Meal[] = [
  {
    id: '1',
    name: 'Butter Chicken',
    restaurant: 'Punjab Grill',
    image: butterChicken,
    price: 249,
    prepTime: 15,
    rating: 4.9,
    category: 'North Indian',
    isExpress: true,
  },
  {
    id: '2',
    name: 'Masala Dosa',
    restaurant: 'Saravana Bhavan',
    image: masalaDosa,
    price: 129,
    prepTime: 10,
    rating: 4.8,
    category: 'South Indian',
    isExpress: true,
  },
  {
    id: '3',
    name: 'Hyderabadi Biryani',
    restaurant: 'Paradise Biryani',
    image: hyderabadiBiryani,
    price: 299,
    prepTime: 20,
    rating: 4.9,
    category: 'Biryani',
  },
  {
    id: '4',
    name: 'Cheese Pizza',
    restaurant: 'Pizza Express',
    image: pizza,
    price: 149,
    prepTime: 10,
    rating: 4.6,
    category: 'Biryani',
    isExpress: true,
  },
  {
    id: '5',
    name: 'Paneer Tikka',
    restaurant: 'Barbeque Nation',
    image: paneerTikka,
    price: 199,
    prepTime: 12,
    rating: 4.8,
    category: 'North Indian',
    isExpress: true,
  },
  {
    id: '6',
    name: 'Chole Bhature',
    restaurant: "Haldiram's",
    image: choleBhature,
    price: 149,
    prepTime: 10,
    rating: 4.6,
    category: 'North Indian',
    isExpress: true,
  },
  {
    id: '7',
    name: 'Idli Sambar',
    restaurant: 'Saravana Bhavan',
    image: idliSambhar,
    price: 99,
    prepTime: 8,
    rating: 4.7,
    category: 'South Indian',
    isExpress: true,
  },
  {
    id: '8',
    name: 'Vada Pav',
    restaurant: 'Mumbai Street',
    image: vadaPav,
    price: 49,
    prepTime: 5,
    rating: 4.5,
    category: 'Street Food',
    isExpress: true,
  },
  {
    id: '9',
    name: 'Dal Makhani',
    restaurant: 'Punjab Grill',
    image: dalMakhani,
    price: 179,
    prepTime: 15,
    rating: 4.8,
    category: 'North Indian',
    isExpress: true,
  },
  {
    id: '10',
    name: 'Gulab Jamun',
    restaurant: "Haldiram's",
    image: gulabJamun,
    price: 89,
    prepTime: 5,
    rating: 4.9,
    category: 'Dessert',
    isExpress: true,
  },
  {
    id: '11',
    name: 'Rajasthani Thali',
    restaurant: 'Rajdhani',
    image: rajasthaniThali,
    price: 399,
    prepTime: 20,
    rating: 4.9,
    category: 'Thali',
  },
  {
    id: '12',
    name: 'Lucknowi Biryani',
    restaurant: 'Dum Pukht',
    image: lucknowiBiryani,
    price: 329,
    prepTime: 25,
    rating: 4.8,
    category: 'Biryani',
  },
  {
    id: '13',
    name: 'Samosa (2 pcs)',
    restaurant: "Haldiram's",
    image: samosa,
    price: 40,
    prepTime: 5,
    rating: 4.6,
    category: 'Street Food',
    isExpress: true,
  },
  {
    id: '14',
    name: 'Chocolate Donut',
    restaurant: 'Dunkin',
    image: chocolateDonuts,
    price: 45,
    prepTime: 3,
    rating: 4.5,
    category: 'Dessert',
    isExpress: true,
  },
  {
    id: '15',
    name: 'Poha',
    restaurant: 'Home Kitchen',
    image: poha,
    price: 60,
    prepTime: 8,
    rating: 4.5,
    category: 'Breakfast',
    isExpress: true,
  },
  {
    id: '16',
    name: 'Palak Paneer',
    restaurant: 'Punjab Grill',
    image: palakPaneer,
    price: 199,
    prepTime: 20,
    rating: 4.7,
    category: 'North Indian',
  },
  {
    id: '17',
    name: 'Chicken Korma',
    restaurant: 'Dum Pukht',
    image: chickenKorma,
    price: 269,
    prepTime: 22,
    rating: 4.7,
    category: 'North Indian',
  },
  {
    id: '18',
    name: 'Kadai Paneer',
    restaurant: 'Barbeque Nation',
    image: kadaiPaneer,
    price: 219,
    prepTime: 20,
    rating: 4.7,
    category: 'North Indian',
  },
  {
    id: '19',
    name: 'Butter Garlic Naan',
    restaurant: 'Punjab Grill',
    image: butterGarlicNaan,
    price: 59,
    prepTime: 8,
    rating: 4.8,
    category: 'Bread',
  },
  {
    id: '20',
    name: 'Mutton Rogan Josh',
    restaurant: 'Dum Pukht',
    image: muttonRoganJosh,
    price: 349,
    prepTime: 30,
    rating: 4.8,
    category: 'North Indian',
  },
  {
    id: '21',
    name: 'Prawn Masala',
    restaurant: 'Coastal Kitchen',
    image: prawnMasala,
    price: 399,
    prepTime: 25,
    rating: 4.7,
    category: 'Seafood',
  },
];

export const mockTimeSlots: TimeSlot[] = [
  { id: '1', time: '11:30 AM', queueLevel: 'low',    availableSlots: 8,  estimatedWait: 0 },
  { id: '2', time: '12:00 PM', queueLevel: 'medium', availableSlots: 4,  estimatedWait: 3 },
  { id: '3', time: '12:30 PM', queueLevel: 'high',   availableSlots: 1,  estimatedWait: 8 },
  { id: '4', time: '1:00 PM',  queueLevel: 'medium', availableSlots: 5,  estimatedWait: 2 },
  { id: '5', time: '1:30 PM',  queueLevel: 'low',    availableSlots: 10, estimatedWait: 0 },
  { id: '6', time: '2:00 PM',  queueLevel: 'low',    availableSlots: 12, estimatedWait: 0 },
];

export const mockUserMetrics: UserMetrics = {
  timeSaved: 47,
  loyaltyPoints: 2450,
  activeOrders: 2,
  ordersThisMonth: 18,
  streak: 7,
  foodWasteReduced: 2.7,
  queueTimesSaved: 340,
};